import React from 'react';
import { motion } from 'framer-motion';

export const Terms: React.FC = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.2
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { 
      opacity: 1, 
      y: 0,
      transition: { duration: 0.8, ease: "easeOut" }
    }
  };

  return (
    <motion.section 
      initial="hidden"
      animate="visible"
      exit={{ opacity: 0 }}
      className="min-h-screen bg-cream pt-32 pb-24 px-6 md:px-12"
    >
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, ease: "easeOut" }}
        >
          <h1 className="font-serif text-5xl md:text-7xl text-charcoal mb-12">Terms of Service</h1>
          
          <motion.div 
            variants={containerVariants}
            className="space-y-12 text-charcoal/80 font-light leading-relaxed text-lg"
          >
            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">1. Acceptance of Terms</h3>
              <p>
                By accessing and using the Nexora Patent AI website and services ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service.
              </p>
            </motion.div>

            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">2. Description of Service</h3>
              <p>
                Nexora Patent AI provides an AI-powered platform for assisting in the drafting of patent applications. The Service is a productivity tool and does not constitute legal advice. You acknowledge that any output generated by the Service should be reviewed by a qualified patent attorney or agent.
              </p>
            </motion.div>

            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">3. User Accounts</h3>
              <p>
                To access certain features of the Service, you may be required to register for an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
              </p>
            </motion.div>

            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">4. Intellectual Property</h3>
              <p>
                The Service and its original content (excluding Content provided by users), features, and functionality are and will remain the exclusive property of Nexora Patent AI and its licensors. The Service is protected by copyright, trademark, and other laws of the United States and foreign countries.
              </p>
            </motion.div>

            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">5. Limitation of Liability</h3>
              <p>
                In no event shall Nexora Patent AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
            </motion.div>
            
            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">6. Governing Law</h3>
              <p>
                These Terms shall be governed and construed in accordance with the laws of Delaware, USA, without regard to its conflict of law provisions.
              </p>
            </motion.div>

            <motion.div variants={itemVariants}>
              <h3 className="font-serif text-2xl text-charcoal mb-4">7. Contact Us</h3>
              <p>
                If you have any questions about these Terms, please contact us at: <a href="mailto:info@nexorapatent.com" className="underline text-charcoal">info@nexorapatent.com</a>.
              </p>
            </motion.div>
          </motion.div>
        </motion.div>
      </div>
    </motion.section>
  );
};